# Generated by Django 5.1.1 on 2024-09-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="google_calendar_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
